import { z } from "zod";

export const STATES = [
    "AK",
    "AL",
    "AR",
    "AS",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "GA",
    "GU",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "PR",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VI",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY",
  ] as const;



export const profileSchema = z.object({
  fullName: z.string({ required_error: "Name is required" }).min(1).max(50),
  address1: z.string({ required_error: "Address 1 is required" }).max(100),
  address2: z.string().max(100).optional(),
  city:z.string({ required_error: "City is required" }).max(100),
  // be careful, enum or string?
  state: z.enum(STATES),
  zipcode: z.string().min(5).max(9),
});

export type profileSchemaType = z.infer<typeof profileSchema>;