services:
  test-db:
    image: postgres
    restart: always
    container_name: cosc4353
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test